### ISSUE TITLE
[DEPR]: Blockstore

### ISSUE THREAD

**Issue by kdmccormick** [openedx/blockstore#314]
### Proposal Date

2024-02-01

### Target Ticket Acceptance Date

2024-02-15

### Earliest Open edX Named Release Without This Functionality

Redwood - 2024-04

### Rationale

If you’ve been following Open edX core development for a while, you might be surprised to see a deprecation notice for Blockstore, which we’d long thought of as the future of Open edX content storage. Rest assured, we’re still actively working on the original goals of Blockstore, but they’re now part of a more fleshed-out package: the [“Learning Core”](https://github.com/openedx/openedx-learning/tree/main/openedx_learning/core).

Some Context: Blockstore was developed in ~2018 as a content storage service, enabling courses.edx.org to serve content for the [LabXchange](https://www.labxchange.org/) project. The broader vision was to replace the Open edX platform’s current storage backend (Modulestore) with something simpler and more flexible, supporting a paradigm shift towards modular, non-linear, and adaptive learning content. The key tenets of Blockstore were that:
* It was **isolated from the complexities** of edx-platform. This made the system easier to comprehend and maintain.
* Its data model was **authoring-first**: its primitives were “bundles” and “assets”, which get versioned and published together. In contrast, Modulestore focuses on content blocks and structures.
* It was **agnostic to the structure of the content** it managed: bundles might be libraries, units, individual components; bundles may contain XBlocks, or something different. In contrast, Modulestore assumes that everything is an XBlock and that everything is part of a Course.

You can read more in Blockstore’s [DESIGN doc](https://github.com/openedx/blockstore/blob/master/DESIGN.rst). Blockstore was selected as the basis for the “Content Libraries V2” initiative, which aimed to rebuild the legacy Content Libraries feature to be more robust and broadly useful. It was envisioned that all Open edX content, including traditional courses, would eventually be migrated to Blockstore, and that Modulestore would be deprecated.

However, in the intervening years, LabXchange moved off of the Open edX platform, and the Content Libraries V2 project was delayed several times due to organizational shifts and competing priorities. As of 2023, we are not aware of any production users of Blockstore (if you are aware of any, please comment).

Since 2018, and especially since the creation of Axim in 2021, we have had time to learn lessons from Blockstore’s original design and think deeply about the needs of the Open edX project going forward. We still believe in Blockstore’s original key tenets, but we've also learned more:

* Whereas Blockstore stores almost all of its data on object storage (e.g. S3), we should store data in a **relational database** like MySQL and connect it LMS/CMS **in-process library**. One of the assumptions in the Blockstore design was the Open edX CMS (running in the same deployment) would be able to query this data very quickly, but in practice we found that reading data from S3 had significantly higher latency than anticipated, causing XBlocks to load very slowly and making additional complex layers of caching absolutely necessary. The vast majority of production issues with Blockstore were either Object Storage errors (expired signed URLs) or cache invalidation errors.
* Whereas Blockstore (being authoring-first) assumed that some other system would consume and cache its content for **efficient loading/filtering/searching/sorting in LMS**, we’re better off just building the basis of that “some other system” into the same package as the storage backend. edx-platform developers need a good, consistent pattern for representing learning content; there is [guidance for doing so today](https://github.com/openedx/edx-platform/blob/master/docs/decisions/0011-limit-modulestore-use-in-lms.rst), but it’s better for everyone if that pattern is provided as a core capability.
* Whereas Blockstore managed versions at the abstract “bundle” level, we’re better off managing **versions for individual learning components**. That way, edx-platform, et al, do not need to “choose” what a bundle means in any given context–everything is versioned, so clients just need to choose how to helpfully present that to authors. This still lets us be agnostic as to the shape and structure of the content, as we’re not making assumptions about how the components fit together. It also lets us support extremely large libraries with many thousands of components which, under Blockstore’s bundle-versioning system, introduced performance issues during writes.

### Removal

* Blockstore reference need to be removed from edx-platform.
* Docs referencing Blockstore concepts should be updated or archived.
* Blockstore itself needs to be archived.

### Replacement

We've developed the [**Learning Core**](https://github.com/openedx/openedx-learning/tree/main/openedx_learning/core), which replaces Blockstore and incorporates what we've learned over the past few years. The insights of Blockstore live on mostly in the `openedx_learning.core.publishing` sub-package. You can read the various [decisions we’ve made](https://github.com/openedx/openedx-learning/tree/main/docs/decisions) and [are making](https://github.com/openedx/openedx-learning/issues) for this new system.

### Deprecation

We will add deprecation notice to Blockstore's README. We'll also push a final Blockstore release to PyPI so that the deprecation notice shows up there.

### Migration

Because Blockstore isn’t currently deployed to production anywhere (again, please comment if you disagree), we have the great opportunity to jump right to Learning Core rather than foisting a two-step Modulestore->Blockstore->LC migration upon site operators. So, we are currently migrating the Content Libraries Relaunch project from Blockstore to the Learning Core, which we are aiming to make experimentally available as early as Redwood (June 2024) and properly available by Sumac (December 2024). We plan to remove Blockstore from the release starting with Redwood. Going forward, we plan to incrementally migrate parts of edx-platform the Learning Core, with the long-term goal of either replacing Modulestore, or reducing Modulestore to a compatibility layer resting on top of a backfilled Learning Core.

### Additional Info

N/A

### Task List

- [ ] Add DEPR notice to README of https://github.com/openedx/blockstore. Push a final release to PyPI.
- [ ] https://github.com/openedx/edx-platform/pull/34066
- [ ] Remove the Blockstore XBlock-runtime.
- [ ] Remove Blockstore from edx-platform requirements and INSTALLED_APPS.
- [ ] Remove
- [ ] Archive https://github.com/openedx/blockstore
- [ ] Search and update/archive docs containing the words "blockstore", "bundleversion", "snapshot", etc.

**Comment by regisb** [comment]
Yes, this is a surprising announcement! But your thorough explanations really help to understand the situation. 

I just have a question on that specific item:

> Whereas Blockstore stores almost all of its data on object storage (e.g. S3), we should store data in a relational database like MySQL and connect it LMS/CMS via an in-process library.

At the time [Blockstore was designed](https://openedx.atlassian.net/wiki/spaces/AC/pages/737149430/Blockstore+Design) I made the [following comment](https://openedx.atlassian.net/wiki/spaces/AC/pages/737149430/Blockstore+Design?focusedCommentId=916848704): 

> I'm a bit surprised by the choice of files for storing content. My 2 cents:
> 
> 1. The data structure should be chosen by taking into consideration what kind of read/write access will be required. For instance, file systems are not good at answering the question "what is the most recent file in this folder" (they don't have an index on dates). And, it seems to me that we are frequently going to have to make such queries, for instance to get the latest version of a content element.
> 2. Filesystems are bad at searching: will we have to rely on a grep-like tool (i.e: slow) when searching for content?
> 3. Separating data in two different storage systems (filesystem and SQL db) requires some synchronization, which is a hard problem. 
> 4. ...
> 5. Files don't have schema: one of the current major issues with xblocks is that they are extremely difficult to migrate, whenever their definition changes. Backward compatibility becomes very hard to maintain. Files have the same problem.

To which Dave made a [very sensible answer](https://github.com/openedx/blockstore/issues/29) that S3 is cheap while databases are expensive -- totally reasonable answer, especially in the context of a large site like edX.org.

So, I'm wondering how the new Learning Core handles storage costs? Also, it has to provide search capabilities. How do we achieve that? Is data automatically synced with Elasticsearch? If yes, how?

I guess I could read the [existing ADRs](https://github.com/openedx/openedx-learning/tree/main/docs/decisions) and the [openedx-learning](https://github.com/openedx/openedx-learning) source code to find the answer... but that's a lot of content to parse. If someone could give me a few pointers, I would really appreciate it.

**Comment by ormsbee** [comment]
Looking back at a high level, I believe I made the following missteps with Blockstore:

* I assumed Blockstore would be authoring-only, and we would make a simpler published-only data model in the LMS. Learning Core started with the goal of implementing that LMS-oriented published-only data model.
* I couldn't think of an efficient-enough representation that would support our fully granular, versioned content in a relational database.

So I tried to optimize a pattern that was already familiar to me with Modulestore–snapshots of content, with versions only tracked at the highest level (a full course or library). We would build on that by tracking the dependencies between those top level entities in the database. But a number of things came up as we were building on the data model:

**We kept finding requirements that required us to keep multiple concurrent versions in the LMS** (such as previewing, or using a fixed version of Library content). Once Learning Core had to hold many versions anyway, it lost a lot of the hoped-for data model simplicity.

**Blockstore ended up serving content directly to users anyway.** This was something that we explicitly wanted to avoid (and even called out in the original design goals/non-goals)... but it happened anyway, and performance was poor. That being said, we had authoring performance issues for larger libraries anyway, due to worse-than-expected S3 latency issues.

**We figured out a more efficient representation for versions and parent-child relationships.** Shifting versioning to happen at the Component level and allowing container types like Units to be defined with "unpinned" Component children is what makes this work. If we had kept the Modulestore/Blockstore pattern of snapshots, it would have exploded the storage requirements and made a shift to MySQL prohibitively costly. Figuring this out took a lot of iteration though, dating back to https://github.com/openedx/openedx-learning/issues/1.

**Comment by kdmccormick** [comment]
This now Accepted. Code removal is in progress.
